- name: Update apt packages
  apt:
    update_cache: yes
  become: true

- name: Install Node.js and npm
  apt:
    name: ['nodejs', 'npm']
    state: present
  become: true

- name: Clone the Node.js app repository
  git:
    repo: "https://github.com/AruneshDwivedi/aws-nodejs-cicd.git"
    dest: /home/ubuntu/app
    version: main

- name: Install dependencies
  npm:
    path: /home/ubuntu/app/app
    production: true

- name: Start Node.js app
  shell: |
    nohup node /home/ubuntu/app/app/server.js > /home/ubuntu/app.log 2>&1 &
  args:
    executable: /bin/bash
